// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Top-level configuration for the proxy engine.
class EngineConfig {
  /// Size of each download chunk in bytes.
  final BigInt chunkSize;

  /// Maximum number of concurrent download tasks.
  final int maxConcurrency;

  /// Directory used for on-disk cache files.
  final String cacheDir;

  const EngineConfig({
    required this.chunkSize,
    required this.maxConcurrency,
    required this.cacheDir,
  });

  @override
  int get hashCode =>
      chunkSize.hashCode ^ maxConcurrency.hashCode ^ cacheDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineConfig &&
          runtimeType == other.runtimeType &&
          chunkSize == other.chunkSize &&
          maxConcurrency == other.maxConcurrency &&
          cacheDir == other.cacheDir;
}
